# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='static/CompanyLogos/')),
                ('description', models.TextField(max_length=10000)),
                ('address', models.CharField(max_length=500)),
                ('website', models.CharField(max_length=500)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stipend', models.IntegerField(max_length=20)),
                ('startdate', models.CharField(max_length=10)),
                ('enddate', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=10000)),
                ('qualification', models.TextField(max_length=10000)),
                ('type', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships.industry')),
            ],
        ),
    ]
