# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-30 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_auto_20171230_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='internship',
            name='startdate',
            field=models.DateField(),
        ),
    ]
