# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0005_confirmedinternships_internshiprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndestrialVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('ratings', models.IntegerField()),
                ('isavailable', models.CharField(choices=[('a', 'available'), ('na', 'not avoialable')], default='na', max_length=2)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships.industry')),
            ],
        ),
    ]
