# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0006_indestrialvisit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndestrialVisit',
            new_name='IndustrialVisit',
        ),
    ]
