# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0007_auto_20180103_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrialvisit',
            name='ratings',
            field=models.FloatField(),
        ),
    ]
