# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 09:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0009_auto_20180123_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='ivrequest',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='doneiv',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
