# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0010_auto_20180125_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
