# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionPapers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='paper',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='college',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='college',
            new_name='school',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.AddField(
            model_name='papers',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionPapers.College'),
        ),
        migrations.AddField(
            model_name='papers',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionPapers.Subject'),
        ),
    ]
