# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionPapers', '0002_auto_20171222_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='school',
            new_name='college',
        ),
    ]
