# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionPapers', '0003_auto_20171222_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='paper',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
