# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionPapers', '0004_papers_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='paper',
            field=models.FileField(upload_to='static/papersDir/'),
        ),
    ]
