# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionPapers', '0005_auto_20171229_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='term',
            field=models.CharField(default='', max_length=10),
        ),
    ]
