# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0008_auto_20180103_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruitments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=1000)),
                ('salary', models.IntegerField()),
                ('description', models.TextField(max_length=10000)),
                ('qualifications', models.TextField(max_length=500)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships.industry')),
            ],
        ),
    ]
