# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitments',
            name='description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='recruitments',
            name='qualifications',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recruitments',
            name='type',
            field=models.CharField(max_length=1000),
        ),
    ]
