# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_profile_resume'),
        ('recruitments', '0002_auto_20180113_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedRecruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='recruitmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='recruitments',
            new_name='recruitment',
        ),
        migrations.AddField(
            model_name='recruitmentrequest',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitments.recruitment'),
        ),
        migrations.AddField(
            model_name='recruitmentrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Profile'),
        ),
        migrations.AddField(
            model_name='confirmedrecruitment',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitments.recruitment'),
        ),
        migrations.AddField(
            model_name='confirmedrecruitment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Profile'),
        ),
    ]
