# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 13:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0005_profile_resume'),
        ('internships', '0010_auto_20180125_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateConf', models.DateField()),
                ('letter', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=10000)),
                ('number', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=20)),
                ('isavailable', models.CharField(choices=[('yes', 'available'), ('no', 'not available')], default='yes', max_length=3)),
                ('minimumCnt', models.IntegerField(default=3)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships.industry')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='projectnotice',
            name='ProjectRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectRequest'),
        ),
        migrations.AddField(
            model_name='projectnotice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Profile'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='ProjectRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectRequest'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Profile'),
        ),
        migrations.AddField(
            model_name='acceptedgroup',
            name='ProjectRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectRequest'),
        ),
    ]
